import { NextApiRequest, NextApiResponse } from 'next'
import { generateText, tool } from 'ai'
import { createOpenAI } from '@ai-sdk/openai'
import { z } from 'zod'

const openai = process.env.OPENAI_API_KEY ? createOpenAI({ apiKey: process.env.OPENAI_API_KEY }) : null;

// Multi-Agent LLM Routing Layer (Research, Analysis, Execution)
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' })
    }

    const { message } = req.body

    if (!message) {
        return res.status(400).json({ error: 'Message is required' })
    }

    // Default Fallback simulated AI if API key is absent (e.g. initial setup)
    if (!openai) {
        let reply = "I am the Broker AI routing agent. (Simulated Mode - No API Key). I'm analyzing your portfolio against the Quant Engine."

        if (message.toLowerCase().includes('rsi')) {
            reply = "According to our RSI indicators, you currently have no stocks exhibiting oversold behavior (RSI < 30)."
        } else if (message.toLowerCase().includes('macd') || message.toLowerCase().includes('momentum')) {
            reply = "Your core tech holdings are showing negative MACD momentum histograms. Consider maintaining a cash buffer to hedge against volatility."
        } else if (message.toLowerCase().includes('vix') || message.toLowerCase().includes('discount')) {
            reply = "The current VIX is high (Simulated 35). Based on our Composite Scoring model, I've applied a +5 point bullish discount to all oversold stocks today since panic brings opportunity."
        } else if (message.toLowerCase().includes('buy') || message.toLowerCase().includes('sell')) {
            reply = "Any execution orders generated by me require your manual confirmation. Let's look at the Bollinger Bands before confirming that trade."
        }

        // Simulate network latency for the Assistant
        await new Promise(resolve => setTimeout(resolve, 800))

        return res.status(200).json({
            role: 'assistant',
            content: reply,
            timestamp: new Date().toISOString()
        })
    }

    try {
        const { text } = await generateText({
            model: openai('gpt-4o'),
            system: `You are the Gyanooz Stock Portfolio AI Assistant and Router.
You have tools to analyze technical indicators (Research Agent), review current holdings (Analysis Agent), and prepare orders (Execution Agent).
For any buy and sell operations, you must remind the user that execution requires manual confirmation in the app GUI. Be proactive but safe.`,
            prompt: message,
            tools: {
                checkIndicator: tool({
                    description: 'Get the state of technical indicators like RSI, MACD, or Bollinger Bands for a given stock symbol.',
                    parameters: z.object({
                        indicator: z.enum(['RSI', 'MACD', 'Bollinger Bands', 'EMA', 'SMA']),
                        symbol: z.string()
                    }),
                    // @ts-ignore
                    execute: async (args: any) => {
                        const { indicator, symbol } = args;
                        console.log(`[Quant Engine Tool] Checking ${indicator} for ${symbol}`)
                        switch (indicator) {
                            case 'RSI': return 'RSI is 45 (Neutral)'
                            case 'MACD': return 'MACD is -1.5 (Bearish momentum)'
                            case 'Bollinger Bands': return 'Price is near the lower band (Oversold condition)'
                            default: return 'No significant signal'
                        }
                    }
                }),
                fetchPortfolio: tool({
                    description: 'Get the current user portfolio summary and cash balance.',
                    parameters: z.object({}),
                    // @ts-ignore
                    execute: async () => {
                        console.log(`[Upstox Tool] Fetching holding portfolio`)
                        return 'Portfolio contains RELIANCE, TCS, INFY. Total value is 10,000. Cash available: 5,000.'
                    }
                }),
                prepareOrder: tool({
                    description: 'Prepare an execution order for the user to confirm.',
                    parameters: z.object({
                        action: z.enum(['BUY', 'SELL']),
                        symbol: z.string(),
                        quantity: z.number()
                    }),
                    // @ts-ignore
                    execute: async (args: any) => {
                        const { action, symbol, quantity } = args;
                        console.log(`[Upstox Tool] Preparing order ${action} for ${quantity} of ${symbol}`)
                        return `Successfully drafted to ${action} ${quantity} shares of ${symbol}. Remind the user they need to click Confirm Order in the chat UI.`
                    }
                })
            }
        });

        return res.status(200).json({
            role: 'assistant',
            content: text,
            timestamp: new Date().toISOString()
        })
    } catch (error) {
        console.error("AI Routing Layer Error:", error)
        return res.status(500).json({ error: 'Failed to generate model response.', details: String(error) })
    }
}
