import Link from "next/link"

export const metadata = {
  title: "Terms of Service — Invest Buddy AI",
}

const EFFECTIVE_DATE = "6 March 2026"
const VERSION = "Beta v1.0"

export default function TermsPage() {
  return (
    <div className="prose prose-invert prose-sm max-w-none">
      {/* Header */}
      <div className="not-prose mb-10">
        <p className="text-xs font-mono text-violet-400/60 uppercase tracking-widest mb-2">Legal</p>
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <div className="flex flex-wrap items-center gap-3 text-xs text-white/40">
          <span>Effective: {EFFECTIVE_DATE}</span>
          <span>·</span>
          <span className="rounded-full bg-violet-500/15 border border-violet-400/20 text-violet-400 px-2 py-0.5">{VERSION}</span>
        </div>
        <p className="mt-4 text-white/50 text-sm leading-relaxed">
          These Terms of Service (<strong className="text-white/70">"Terms"</strong>) govern your access to and use of{" "}
          <strong className="text-white/70">Invest Buddy AI</strong>, a web application operated by{" "}
          <strong className="text-white/70">Upflow Sprint Private Limited</strong> ("Company", "we", "us", or "our"), a company
          registered in India. By registering for or using the platform, you agree to these Terms in full. If you do not agree,
          you must not use the platform.
        </p>
      </div>

      {/* ── 1. Definitions ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">1. Definitions</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li><strong className="text-white/80">"Platform"</strong> — the Invest Buddy AI web application available at investbuddyai.com and any associated APIs or mobile interfaces.</li>
          <li><strong className="text-white/80">"User" / "you"</strong> — any individual or entity that creates an account or accesses the Platform.</li>
          <li><strong className="text-white/80">"Beta User"</strong> — a User onboarded during the current beta testing phase of the Platform.</li>
          <li><strong className="text-white/80">"Portfolio Data"</strong> — holdings, transaction history, and financial data fetched from a connected brokerage account on your behalf.</li>
          <li><strong className="text-white/80">"Algorithmic Output"</strong> — any score, signal, indicator, ranking, or recommendation generated by the Platform's quantitative engine.</li>
          <li><strong className="text-white/80">"Third-Party Advisor Data"</strong> — publicly available buy/sell/hold signals and target prices published by SEBI-registered research analysts or brokerages, which the Platform aggregates as an input to its computations.</li>
        </ul>
      </section>

      {/* ── 2. Nature of the Service ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">2. Nature of the Service — NOT Investment Advice</h2>
        <div className="rounded-xl border border-amber-400/25 bg-amber-400/5 px-5 py-4 mb-4">
          <p className="text-sm font-semibold text-amber-400 mb-1">Important Notice</p>
          <p className="text-sm text-amber-300/70">
            Invest Buddy AI is <strong>not</strong> a SEBI-registered investment adviser, research analyst, portfolio manager,
            or stockbroker. The Platform does not provide investment advice, financial advice, or any personalised
            recommendation to buy, sell, or hold any security.
          </p>
        </div>
        <ul className="space-y-3 text-white/60 text-sm">
          <li>2.1 All Algorithmic Outputs are the result of mathematical and statistical computations performed on market data,
            portfolio data, and publicly available third-party advisory signals. They are <em>information tools</em>, not
            directives or recommendations.</li>
          <li>2.2 You are solely responsible for all investment decisions. The Company shall not be held liable for any
            financial loss arising from your reliance on Platform outputs.</li>
          <li>2.3 The Platform allows you to configure the weighting parameters of the scoring algorithm. By doing so, you
            exercise your own judgement and the resulting outputs reflect your own configured logic — not Company advice.</li>
          <li>2.4 Third-Party Advisor Data aggregated by the Platform is published by independent SEBI-registered entities.
            The Company does not endorse, verify, or guarantee the accuracy of such data.</li>
          <li>2.5 <strong className="text-white/70">There is no automated trading on this Platform.</strong> No order is placed
            in your brokerage account without your explicit, manual confirmation within the Platform's Trade interface.</li>
        </ul>
      </section>

      {/* ── 3. Eligibility ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">3. Eligibility</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>3.1 You must be at least 18 years of age to use the Platform.</li>
          <li>3.2 You must have a valid, legally operating brokerage account in India to use Portfolio integration features.</li>
          <li>3.3 During the beta phase, access is by invitation or application only. The Company reserves the right to accept or reject any registration at its sole discretion.</li>
        </ul>
      </section>

      {/* ── 4. Beta Access ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">4. Beta Access & Testing Phase</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>4.1 The Platform is currently in a <strong className="text-white/70">closed beta</strong>. All current Users are beta testers.</li>
          <li>4.2 Beta access is granted to test features, provide feedback, and identify bugs. By accepting these Terms, you agree to participate in an <em>early, non-production version</em> of the Platform.</li>
          <li>4.3 During beta: features may change, be removed, or be temporarily unavailable without notice; data may be reset; no uptime or performance SLA applies.</li>
          <li>4.4 The Company may terminate or modify beta access at any time without liability.</li>
          <li>4.5 When the Platform transitions to general availability, separate Terms applicable to the production version will supersede this beta edition. Beta users will be notified and given an opportunity to review and accept updated terms.</li>
        </ul>
      </section>

      {/* ── 5. Account & Security ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">5. Account Registration & Security</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>5.1 You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>5.2 You agree to provide accurate information at registration and keep it current.</li>
          <li>5.3 You must notify us immediately at legal@upflowsprint.com if you suspect unauthorised access to your account.</li>
          <li>5.4 API keys you provide for third-party services (Upstox, LLM providers) are stored in encrypted form. You are responsible for the validity and security of those keys.</li>
          <li>5.5 Each account is for a single individual user. Corporate or shared access is not permitted without prior written consent.</li>
        </ul>
      </section>

      {/* ── 6. Brokerage Integration ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">6. Brokerage Integration & Order Execution</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>6.1 When you connect a brokerage account (e.g., Upstox via OAuth 2.0), you authorise the Platform to read your holdings and positions, and to submit orders only upon your explicit, real-time, manual confirmation.</li>
          <li>6.2 <strong className="text-white/70">The Platform does not execute algorithmic or automated trades.</strong> Every order requires a deliberate action by you within the Trade screen.</li>
          <li>6.3 You remain solely responsible for all orders placed via your brokerage account, including orders submitted through the Platform.</li>
          <li>6.4 The Company is not a broker and does not hold or process funds. All order execution occurs through your own registered brokerage account under that broker's own terms.</li>
          <li>6.5 The Platform's brokerage integration features are subject to the terms and availability of the respective brokerages' APIs.</li>
        </ul>
      </section>

      {/* ── 7. Acceptable Use ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">7. Acceptable Use</h2>
        <p className="text-white/60 text-sm mb-3">You agree not to:</p>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>7.1 Use the Platform for any unlawful purpose or in violation of any applicable Indian or international law, including SEBI regulations.</li>
          <li>7.2 Attempt to reverse-engineer, scrape, or extract any proprietary algorithm, model, or database from the Platform.</li>
          <li>7.3 Share your account credentials or allow third parties to access the Platform on your behalf.</li>
          <li>7.4 Use the Platform to build competing products or services.</li>
          <li>7.5 Submit false, misleading, or fraudulent information.</li>
          <li>7.6 Attempt to interfere with, disrupt, or gain unauthorised access to the Platform's infrastructure.</li>
        </ul>
      </section>

      {/* ── 8. Intellectual Property ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">8. Intellectual Property</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>8.1 All software, design, branding, and documentation forming part of the Platform is the intellectual property of Upflow Sprint Private Limited.</li>
          <li>8.2 You retain ownership of your personal financial data. You grant the Company a limited, non-exclusive licence to process that data solely to provide the Platform's functionality to you.</li>
          <li>8.3 Any feedback, suggestions, or bug reports you submit may be used by the Company to improve the Platform without obligation to you.</li>
        </ul>
      </section>

      {/* ── 9. Disclaimers & Limitation of Liability ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">9. Disclaimers & Limitation of Liability</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>9.1 The Platform is provided on an <strong className="text-white/70">"as-is" and "as-available" basis</strong>, without warranties of any kind, express or implied.</li>
          <li>9.2 To the maximum extent permitted by law, the Company's aggregate liability to you for any claim arising out of or relating to the Platform shall not exceed the amount you paid (if any) for Platform access in the preceding 12 months.</li>
          <li>9.3 The Company shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profit, loss of data, or investment losses.</li>
          <li>9.4 Algorithmic Outputs may be delayed, inaccurate, or incomplete. You should always independently verify information before making investment decisions.</li>
        </ul>
      </section>

      {/* ── 10. Modifications ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">10. Modifications to Terms</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>10.1 We reserve the right to update these Terms at any time. Material changes will be notified via email to your registered address and/or a prominent notice within the Platform.</li>
          <li>10.2 Continued use of the Platform after the effective date of revised Terms constitutes acceptance of those Terms.</li>
          <li>10.3 When the Platform transitions from beta to general availability, updated Terms for the production release will be presented at that time and will require fresh acceptance.</li>
        </ul>
      </section>

      {/* ── 11. Termination ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">11. Termination</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>11.1 You may terminate your account at any time by contacting support@upflowsprint.com.</li>
          <li>11.2 We may suspend or terminate your access for breach of these Terms, suspected fraudulent activity, or at our discretion during the beta phase, with or without prior notice.</li>
          <li>11.3 Upon termination, your right to access the Platform ceases. Data retention and deletion are governed by our Privacy Policy.</li>
        </ul>
      </section>

      {/* ── 12. Governing Law ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">12. Governing Law & Dispute Resolution</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>12.1 These Terms are governed by the laws of India.</li>
          <li>12.2 Any disputes shall first be attempted to be resolved through good-faith negotiation.</li>
          <li>12.3 If unresolved within 30 days, disputes shall be subject to the exclusive jurisdiction of the courts of <strong className="text-white/70">Kolkata, West Bengal, India</strong>.</li>
        </ul>
      </section>

      {/* ── 13. Contact ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">13. Contact</h2>
        <div className="rounded-xl border border-white/[0.07] bg-white/[0.02] px-5 py-4 text-sm text-white/60 space-y-1">
          <p><strong className="text-white/80">Upflow Sprint Private Limited</strong></p>
          <p>Website: <a href="https://upflowsprint.com" className="text-violet-400 hover:text-violet-300" target="_blank" rel="noopener noreferrer">https://upflowsprint.com</a></p>
          <p>Legal queries: legal@upflowsprint.com</p>
          <p>Support: support@upflowsprint.com</p>
        </div>
      </section>

      {/* Navigation */}
      <div className="not-prose mt-10 flex flex-wrap gap-3 text-xs">
        <Link href="/legal/privacy" className="rounded-lg border border-white/10 px-4 py-2 text-white/50 hover:text-white/80 hover:border-white/20 transition-colors">Privacy Policy →</Link>
        <Link href="/legal/disclaimer" className="rounded-lg border border-white/10 px-4 py-2 text-white/50 hover:text-white/80 hover:border-white/20 transition-colors">Financial Disclaimer →</Link>
        <Link href="/legal/beta-agreement" className="rounded-lg border border-white/10 px-4 py-2 text-white/50 hover:text-white/80 hover:border-white/20 transition-colors">Beta Agreement →</Link>
      </div>
    </div>
  )
}
