import Link from "next/link"

export const metadata = {
  title: "Financial Disclaimer — Invest Buddy AI",
}

const EFFECTIVE_DATE = "6 March 2026"
const VERSION = "Beta v1.0"

export default function DisclaimerPage() {
  return (
    <div className="prose prose-invert prose-sm max-w-none">
      {/* Header */}
      <div className="not-prose mb-10">
        <p className="text-xs font-mono text-violet-400/60 uppercase tracking-widest mb-2">Legal</p>
        <h1 className="text-3xl font-bold text-white mb-2">Financial Disclaimer</h1>
        <div className="flex flex-wrap items-center gap-3 text-xs text-white/40">
          <span>Effective: {EFFECTIVE_DATE}</span>
          <span>·</span>
          <span className="rounded-full bg-violet-500/15 border border-violet-400/20 text-violet-400 px-2 py-0.5">{VERSION}</span>
        </div>
      </div>

      {/* ── Primary Warning Banner ── */}
      <div className="not-prose mb-10 rounded-xl border border-amber-400/30 bg-amber-400/8 px-6 py-5 space-y-3">
        <p className="text-base font-bold text-amber-400">Important: Please Read Before Using Invest Buddy AI</p>
        <ul className="text-sm text-amber-300/80 space-y-2">
          <li className="flex gap-2"><span className="text-amber-500 font-bold shrink-0">✕</span> Invest Buddy AI is <strong>NOT</strong> registered with SEBI as an Investment Adviser (IA), Research Analyst (RA), or Portfolio Manager.</li>
          <li className="flex gap-2"><span className="text-amber-500 font-bold shrink-0">✕</span> Invest Buddy AI does <strong>NOT</strong> provide personalised investment advice, financial planning services, or recommendations to buy, sell, or hold any security.</li>
          <li className="flex gap-2"><span className="text-amber-500 font-bold shrink-0">✕</span> Invest Buddy AI does <strong>NOT</strong> perform or facilitate automated, algorithmic, or systematic trading on your behalf.</li>
          <li className="flex gap-2"><span className="text-green-400 font-bold shrink-0">✓</span> Invest Buddy AI is a <strong>computational tool</strong> that performs mathematical and statistical calculations on data you provide and publicly available market information, producing informational outputs that you may use to inform your own, independent investment decisions.</li>
        </ul>
      </div>

      {/* ── 1. Not a SEBI-Registered Entity ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">1. Not a SEBI-Registered Entity</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>1.1 <strong className="text-white/80">Upflow Sprint Private Limited</strong>, the Company that operates Invest Buddy AI, is not registered with the Securities and Exchange Board of India (SEBI) in any capacity — including but not limited to Investment Adviser (IA), Research Analyst (RA), Portfolio Manager, Stockbroker, or Depository Participant.</li>
          <li>1.2 The Company does not hold any SEBI licence permitting the provision of regulated investment services.</li>
          <li>1.3 Nothing on the Platform constitutes or should be construed as a "research report" or "investment advice" as defined under the SEBI (Research Analysts) Regulations, 2014, or the SEBI (Investment Advisers) Regulations, 2013.</li>
        </ul>
      </section>

      {/* ── 2. Nature of Platform Outputs ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">2. Nature of Platform Outputs — Algorithmic Calculations Only</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>2.1 Every score, signal, rank, recommendation indicator, or analytical output generated by Invest Buddy AI is the product of a <strong className="text-white/70">user-configurable mathematical model</strong> that processes:
            <ul className="mt-2 ml-4 space-y-1">
              <li>Your portfolio holdings and financial data (synced from your connected brokerage account)</li>
              <li>Publicly available buy/sell/hold signals and target prices published by SEBI-registered research analysts and brokerages</li>
              <li>Market data from public sources</li>
              <li>Quantitative indicators (e.g., moving averages, momentum, volatility metrics)</li>
            </ul>
          </li>
          <li>2.2 The weighting and configuration of the algorithm's parameters are set <strong className="text-white/70">entirely by you, the user</strong>. Different parameter configurations will produce different outputs. The Platform provides a calculation framework; your configuration provides the decision logic.</li>
          <li>2.3 Third-party advisory signals aggregated by the Platform are published by independent SEBI-registered entities and are made publicly available. The Company does not create, endorse, verify, or guarantee the accuracy, completeness, or currency of these signals.</li>
          <li>2.4 <strong className="text-white/70">Past performance of any signal, indicator, or model output does not guarantee or predict future results.</strong> All investments carry risk, including the risk of total loss of capital.</li>
        </ul>
      </section>

      {/* ── 3. No Automated Trading ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">3. No Automated or Algorithmic Trading</h2>
        <div className="rounded-xl border border-blue-400/20 bg-blue-400/5 px-5 py-4 mb-4">
          <p className="text-sm text-blue-300/80">
            Invest Buddy AI <strong>does not execute trades automatically.</strong> The Platform does not connect to any "algo trading" or "automated order placement" API. All orders require your explicit, real-time, manual confirmation within the Platform's secure Trade interface before any request is submitted to your broker.
          </p>
        </div>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>3.1 The Company does not have the right or authorisation to execute orders in your brokerage account without your explicit, per-order confirmation.</li>
          <li>3.2 The Trade interface is a convenience wrapper around your broker's standard order placement API. Actions you take there are equivalent to placing an order manually through your broker's platform.</li>
          <li>3.3 You are solely responsible for all orders placed — whether submitted via the Platform or directly through your broker.</li>
        </ul>
      </section>

      {/* ── 4. User Responsibility ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">4. User Responsibility for Investment Decisions</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>4.1 You are solely responsible for all investment and trading decisions you make, including any decision influenced by Platform outputs.</li>
          <li>4.2 You should conduct your own independent research and due diligence before making any investment decision.</li>
          <li>4.3 You are strongly encouraged to consult a <strong className="text-white/70">SEBI-registered Investment Adviser</strong> for personalised financial planning and investment advice tailored to your financial situation, risk appetite, and investment goals.</li>
          <li>4.4 Investments in equity markets are subject to market risks. The value of investments can go up or down. Upflow Sprint Private Limited is not liable for any losses, direct or indirect, arising from your use of Platform outputs.</li>
        </ul>
      </section>

      {/* ── 5. No Liability ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">5. Limitation of Liability</h2>
        <ul className="space-y-2 text-white/60 text-sm">
          <li>5.1 To the maximum extent permitted by applicable law, Upflow Sprint Private Limited, its directors, employees, and affiliates shall not be liable for any financial loss, loss of profit, or consequential damages arising from your use of, or reliance upon, any output, feature, or content of the Platform.</li>
          <li>5.2 Platform outputs may be inaccurate, incomplete, or delayed due to data feed latency, algorithm limitations, or technical issues. You should independently verify all outputs before acting on them.</li>
          <li>5.3 This disclaimer does not limit liability for fraud, wilful misconduct, or any liability that cannot be excluded under Indian law.</li>
        </ul>
      </section>

      {/* ── 6. Seek Professional Advice ── */}
      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white border-b border-white/10 pb-2 mb-4">6. Consult a SEBI-Registered Professional</h2>
        <div className="rounded-xl border border-white/[0.07] bg-white/[0.03] px-5 py-4 text-sm text-white/60">
          <p>Before making investment decisions — especially decisions involving significant capital — consider seeking advice from a SEBI-registered Investment Adviser. A registered IA is legally obligated under SEBI regulations to act in your best interest, provide risk-profiled advice, and disclose any conflicts of interest.</p>
          <p className="mt-2">SEBI's register of investment advisers is publicly available at <a href="https://www.sebi.gov.in" className="text-violet-400 hover:text-violet-300" target="_blank" rel="noopener noreferrer">www.sebi.gov.in</a>.</p>
        </div>
      </section>

      {/* Navigation */}
      <div className="not-prose mt-10 flex flex-wrap gap-3 text-xs">
        <Link href="/legal/terms" className="rounded-lg border border-white/10 px-4 py-2 text-white/50 hover:text-white/80 hover:border-white/20 transition-colors">← Terms of Service</Link>
        <Link href="/legal/privacy" className="rounded-lg border border-white/10 px-4 py-2 text-white/50 hover:text-white/80 hover:border-white/20 transition-colors">← Privacy Policy</Link>
        <Link href="/legal/beta-agreement" className="rounded-lg border border-white/10 px-4 py-2 text-white/50 hover:text-white/80 hover:border-white/20 transition-colors">Beta Agreement →</Link>
      </div>
    </div>
  )
}
